# Generated by Django 5.2 on 2025-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name="Légende de l'image"),
        ),
    ]
